version: '3.9'
services:
  webapp:
    image: nefosfatus/hardcodetest:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    build: 
      context: .
      dockerfile: HardCodeTest/Dockerfile
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - mongo
    links:
      - mongo
  mongodb:
    image: mongo
    restart: always
    ports:
    - 27017:27017
    volumes:
    - ${WEBAPP_STORAGE_HOME}/site:/data/db
